# Modelos de analítica avanzada

In [1]:
!pip install git+https://github.com/pycaret/pycaret.git@master --upgrade

Collecting git+https://github.com/pycaret/pycaret.git@master
  Cloning https://github.com/pycaret/pycaret.git (to revision master) to /tmp/pip-req-build-1d9n9gho
  Running command git clone --filter=blob:none --quiet https://github.com/pycaret/pycaret.git /tmp/pip-req-build-1d9n9gho
  Resolved https://github.com/pycaret/pycaret.git to commit 58ec3c282d58e94727f9d5b77b49f241e9103ab3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ipython>=5.5.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (7.34.0)
Requirement already satisfied: ipywidgets>=7.6.5 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (7.7.1)
Requirement already satisfied: tqdm>=4.62.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (4.67.3)
Requirement already satisfied: numpy<1.27,>=1.21 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.26.4)
Requirement already satisfied: pandas<2.2 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.1.4)
Requirement already satisfied: jinja2>=3 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.11.4)
Requirement already satisfied: joblib<1.5,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.4.2)
Requirement already satisfied: scikit-learn<1.5 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.0.7)
Requirement already satisfied: imbalanced-learn<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.13.0)
Requirement already satisfied: category-encoders>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.60.0)
Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.32.4)
Requirement already satisfied: psutil>=5.9.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (5.9.5)
Requirement already satisfied: markupsafe>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.0.3)
Requirement already satisfied: importlib_metadata>=4.12.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (8.7.1)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (5.10.4)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.1.0)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.6.0)
Requirement already satisfied: wurlitzer in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.1.1)
Requirement already satisfied: trio<0.25.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.24.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (75.2.0)
Requirement already satisfied: matplotlib<3.8.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.7.5)
Requirement already satisfied: mljar-scikit-plot in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.3.12)
Requirement already satisfied: yellowbrick>=1.4 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.5)
Requirement already satisfied: plotly>=5.14.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (5.24.1)
Requirement already satisfied: kaleido>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.2.0)
Requirement already satisfied: schemdraw==0.15 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.14.6)
Requirement already satisfied: sktime<0.31.1,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.31.0)
Requirement already satisfied: tbats>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.0.4)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category-encoders>=2.4.0->pycaret==3.4.0) (1.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from deprecation>=2.1.0->pycaret==3.4.0) (26.0)
Requirement already satisfied: sklearn-compat<1,>=0.1 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn<0.14.0,>=0.12.0->pycaret==3.4.0) (0.1.5)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn<0.14.0,>=0.12.0->pycaret==3.4.0) (3.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata>=4.12.0->pycaret==3.4.0) (3.23.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->pycaret==3.4.0) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->pycaret==3.4.0) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->pycaret==3.4.0) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->pycaret==3.4.0) (3.0.16)
Requirement already satisfied: choreographer>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from kaleido>=0.2.1->pycaret==3.4.0) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from kaleido>=0.2.1->pycaret==3.4.0) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from kaleido>=0.2.1->pycaret==3.4.0) (3.11.7)
Requirement already satisfied: pytest-timeout>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from kaleido>=0.2.1->pycaret==3.4.0) (2.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (4.62.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (1.5.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (2.9.0.post0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=4.2.0->pycaret==3.4.0) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat>=4.2.0->pycaret==3.4.0) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat>=4.2.0->pycaret==3.4.0) (5.9.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.55.0->pycaret==3.4.0) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.2->pycaret==3.4.0) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.2->pycaret==3.4.0) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.14.0->pycaret==3.4.0) (9.1.4)
Requirement already satisfied: dash>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from plotly-resampler>=0.8.3.1->pycaret==3.4.0) (4.0.0)
Requirement already satisfied: tsdownsample>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from plotly-resampler>=0.8.3.1->pycaret==3.4.0) (0.1.4.1)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /usr/local/lib/python3.12/dist-packages (from pmdarima>=2.0.4->pycaret==3.4.0) (3.0.12)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from pmdarima>=2.0.4->pycaret==3.4.0) (2.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27.1->pycaret==3.4.0) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27.1->pycaret==3.4.0) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27.1->pycaret==3.4.0) (2026.2.25)
Requirement already satisfied: scikit-base<0.9.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from sktime<0.31.1,>=0.31.0->pycaret==3.4.0) (0.8.3)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.12/dist-packages (from trio<0.25.0,>=0.22.0->pycaret==3.4.0) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<0.25.0,>=0.22.0->pycaret==3.4.0) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<0.25.0,>=0.22.0->pycaret==3.4.0) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<0.25.0,>=0.22.0->pycaret==3.4.0) (1.3.1)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.1.1->kaleido>=0.2.1->pycaret==3.4.0) (3.20.2)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (3.1.3)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (3.1.6)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (4.15.0)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (1.6.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (7.4.9)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (6.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=5.5.0->pycaret==3.4.0) (0.8.6)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret==3.4.0) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret==3.4.0) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret==3.4.0) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret==3.4.0) (4.9.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=5.5.0->pycaret==3.4.0) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.5.0->pycaret==3.4.0) (0.6.0)
Requirement already satisfied: pytest>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret==3.4.0) (8.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret==3.4.0) (1.17.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (6.5.7)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (2.2.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (0.4)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (25.1.0)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (7.17.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (1.3.3)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret==3.4.0) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret==3.4.0) (1.6.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (1.5.1)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (1.4.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (2.8.3)

In [2]:
import pycaret
pycaret.__version__

'3.4.0'

In [3]:
import sysconfig; print(sysconfig.get_paths()["purelib"])

/usr/local/lib/python3.12/dist-packages

In [4]:
from sklearn import  tree
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Multiples modelos

**Ojo! es posible que haya que reiniciar el kernel si estáis en colab!**

In [5]:
import pycaret
from pycaret.datasets import get_data
from pycaret.classification import setup,get_metrics, add_metric, compare_models, evaluate_model

In [6]:
url_file = "https://raw.githubusercontent.com/zng489/Decision_trees_and_Random-Forest-madfhantr-/main/madfhantr.csv"
df = pd.read_csv(url_file)
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [7]:
def preprocessing_madfhantr(df):
  # eliminamos nans
  df = df.dropna()
  # creamos columna con nombres target
  df["targetNames"] = df["Loan_Status"]
  # variables categóricas que tenemos que convertir
  cat_vars = ["Gender","Married","Dependents","Education","Self_Employed","Property_Area","Loan_Status"]
  for cat_var in cat_vars:
    df.loc[:,cat_var] = pd.Categorical(df[cat_var]).codes
  # renombramos la columna target
  df = df.rename(columns={"Loan_Status":"target"})
  df = df.set_index("Loan_ID")
  return df

In [8]:
targetCol = "target"
#df = preprocessing_madfhantr(df).drop("targetNames",axis=1)

In [9]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,target
Loan_ID,,,,,,,,,,,,
LP001003,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,0
LP001005,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,1
LP001006,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,1
LP001008,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,1
LP001011,1,1,2,0,1,5417,4196.0,267.0,360.0,1.0,2,1

In [ ]:
# initialize the setup
# import dataset
from sklearn.metrics import log_loss
clf = setup(df, target = targetCol,imputation_type='simple',fold = 3,train_size=0.7 )
# check all metrics used for model evaluation
get_metrics()
# add Log Loss metric in pycaret
add_metric('logloss', 'LogLoss', log_loss, greater_is_better=False)
# compare baseline models
best = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .             16:03:17
Status     . . . . . . . . . . . . . . . . . .      Fitting 3 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Logistic Regression

Empty DataFrame
Columns: [Model, Accuracy, AUC, Recall, Prec., F1, Kappa, MCC, LogLoss, TT (Sec)]
Index: []

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [ ]:
evaluate_model(best)

Más info: https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb